version: "3.7"
services:
  db:
    container_name: postgres-aoa
    image: "postgres:12.11"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_management
    ports:
      - "5432:5432"